// File: src/screens/services/StyleSheets/BookingScreen.styles.ts
// Purpose: Styles for BookingScreen component

import { StyleSheet } from 'react-native';
import { COLORS } from '../../../constants/theme';

type GetSizeFunction = (small: number, medium: number, large: number, tablet: number, desktop: number) => number;

export const getStyles = (
    isRTL: boolean,
    getSize: GetSizeFunction,
    fontSize: { xs: number; sm: number; base: number; lg: number; xl: number; '2xl': number; '3xl': number },
    iconSize: { sm: number; md: number; lg: number; xl: number }
) => {
    return StyleSheet.create({
        container: { flex: 1, backgroundColor: '#f8fafc' },
        safeArea: { flex: 1 },
        header: {
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: getSize(14, 15, 16, 20, 24),
            paddingVertical: getSize(10, 11, 12, 14, 16),
            backgroundColor: 'white',
            borderBottomWidth: 1,
            borderBottomColor: '#f1f5f9',
        },
        headerTitle: { fontFamily: 'Cairo_700Bold', fontSize: fontSize.base, color: '#1e293b' },
        scrollView: { flex: 1 },
        scrollContent: { padding: getSize(14, 15, 16, 20, 24), paddingBottom: getSize(18, 19, 20, 24, 28) },
        section: {
            backgroundColor: 'white',
            borderRadius: getSize(10, 11, 12, 14, 16),
            padding: getSize(14, 15, 16, 20, 24),
            marginBottom: getSize(10, 11, 12, 14, 16),
            borderWidth: 1,
            borderColor: '#f1f5f9',
        },
        sectionTitle: {
            fontFamily: 'Cairo_700Bold',
            fontSize: fontSize.sm,
            color: '#1e293b',
            textAlign: (isRTL ? 'right' : 'left') as const,
            marginBottom: getSize(10, 11, 12, 14, 16),
        },
        fieldHeader: {
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: getSize(10, 11, 12, 14, 16),
        },
        addNewButton: {
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            alignItems: 'center',
            gap: getSize(4, 5, 6, 7, 8),
            paddingVertical: getSize(6, 7, 8, 9, 10),
            paddingHorizontal: getSize(8, 9, 10, 12, 14),
            borderRadius: getSize(6, 7, 8, 9, 10),
            borderWidth: 1,
            borderColor: COLORS.primary,
            backgroundColor: `${COLORS.primary}08`,
        },
        addNewButtonText: {
            fontFamily: 'Cairo_600SemiBold',
            fontSize: fontSize.xs,
            color: COLORS.primary,
        },
        useSavedButton: {
            marginTop: getSize(8, 9, 10, 12, 14),
            paddingVertical: getSize(6, 7, 8, 9, 10),
            paddingHorizontal: getSize(8, 9, 10, 12, 14),
            borderRadius: getSize(6, 7, 8, 9, 10),
            backgroundColor: '#f8fafc',
            borderWidth: 1,
            borderColor: '#e2e8f0',
        },
        useSavedButtonText: {
            fontFamily: 'Cairo_500Medium',
            fontSize: fontSize.xs,
            color: COLORS.primary,
            textAlign: (isRTL ? 'right' : 'left') as const,
        },
        providerName: {
            fontFamily: 'Cairo_700Bold',
            fontSize: fontSize.base,
            color: '#1e293b',
            textAlign: (isRTL ? 'right' : 'left') as const,
            marginBottom: 4,
        },
        providerCategory: {
            fontFamily: 'Cairo_500Medium',
            fontSize: fontSize.xs,
            color: '#64748b',
            textAlign: (isRTL ? 'right' : 'left') as const,
        },
        serviceItem: {
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            alignItems: 'center',
            paddingVertical: getSize(10, 11, 12, 14, 16),
            borderBottomWidth: 1,
            borderBottomColor: '#f1f5f9',
        },
        serviceItemLast: { borderBottomWidth: 0 },
        serviceInfo: { flex: 1 },
        serviceLabel: {
            fontFamily: 'Cairo_600SemiBold',
            fontSize: fontSize.sm,
            color: '#1e293b',
            textAlign: (isRTL ? 'right' : 'left') as const,
            marginBottom: 4,
        },
        serviceLabelSelected: { color: COLORS.primary },
        servicePrice: {
            fontFamily: 'Cairo_500Medium',
            fontSize: fontSize.xs,
            color: '#64748b',
            textAlign: (isRTL ? 'right' : 'left') as const,
        },
        checkbox: {
            width: getSize(22, 23, 24, 28, 32),
            height: getSize(22, 23, 24, 28, 32),
            borderRadius: getSize(5, 5.5, 6, 7, 8),
            borderWidth: 2,
            borderColor: '#e2e8f0',
            alignItems: 'center',
            justifyContent: 'center',
        },
        checkboxSelected: {
            borderColor: COLORS.primary,
            backgroundColor: COLORS.primary,
        },
        datesContainer: {
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            gap: getSize(6, 7, 8, 10, 12),
        },
        dateCard: {
            width: getSize(66, 68, 70, 80, 90),
            padding: getSize(10, 11, 12, 14, 16),
            borderRadius: getSize(10, 11, 12, 14, 16),
            borderWidth: 1,
            borderColor: '#e2e8f0',
            alignItems: 'center',
        },
        dateCardSelected: {
            borderColor: COLORS.primary,
            backgroundColor: COLORS.primary,
        },
        dateDay: {
            fontFamily: 'Cairo_500Medium',
            fontSize: fontSize.xs,
            color: '#64748b',
            marginBottom: 4,
        },
        dateNumber: {
            fontFamily: 'Cairo_700Bold',
            fontSize: fontSize.base,
            color: '#1e293b',
            marginBottom: 2,
        },
        dateMonth: {
            fontFamily: 'Cairo_500Medium',
            fontSize: fontSize.xs,
            color: '#64748b',
        },
        dateTextSelected: { color: 'white' },
        timeSlotsGrid: {
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            flexWrap: 'wrap',
            gap: getSize(6, 7, 8, 10, 12),
        },
        timeSlot: {
            width: '48%',
            paddingVertical: getSize(10, 11, 12, 14, 16),
            borderRadius: getSize(6, 7, 8, 10, 12),
            borderWidth: 1,
            borderColor: '#e2e8f0',
            alignItems: 'center',
        },
        timeSlotSelected: {
            borderColor: COLORS.primary,
            backgroundColor: COLORS.primary,
        },
        timeSlotText: {
            fontFamily: 'Cairo_600SemiBold',
            fontSize: fontSize.sm,
            color: '#1e293b',
        },
        timeSlotTextSelected: { color: 'white' },
        locationOptions: {
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            gap: getSize(6, 7, 8, 10, 12),
        },
        locationOption: {
            flex: 1,
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            alignItems: 'center',
            justifyContent: 'center',
            gap: getSize(6, 7, 8, 10, 12),
            paddingVertical: getSize(10, 11, 12, 14, 16),
            borderRadius: getSize(6, 7, 8, 10, 12),
            borderWidth: 1,
            borderColor: '#e2e8f0',
        },
        locationOptionSelected: {
            borderColor: COLORS.primary,
            backgroundColor: `${COLORS.primary}08`,
        },
        locationOptionText: {
            fontFamily: 'Cairo_600SemiBold',
            fontSize: fontSize.sm,
            color: '#64748b',
        },
        locationOptionTextSelected: { color: COLORS.primary },
        input: {
            backgroundColor: '#f8fafc',
            borderWidth: 1,
            borderColor: '#e2e8f0',
            borderRadius: getSize(6, 7, 8, 10, 12),
            paddingHorizontal: getSize(10, 11, 12, 14, 16),
            paddingVertical: getSize(10, 11, 12, 14, 16),
            fontFamily: 'Cairo_500Medium',
            fontSize: fontSize.sm,
            color: '#1e293b',
            textAlign: (isRTL ? 'right' : 'left') as const,
        },
        textArea: {
            minHeight: getSize(90, 95, 100, 120, 140),
            textAlignVertical: 'top',
        },
        summarySection: {
            backgroundColor: '#f8fafc',
            borderRadius: getSize(10, 11, 12, 14, 16),
            padding: getSize(14, 15, 16, 20, 24),
            borderWidth: 1,
            borderColor: '#e2e8f0',
            marginBottom: getSize(10, 11, 12, 14, 16),
        },
        summaryRow: {
            flexDirection: (isRTL ? 'row-reverse' : 'row') as const,
            justifyContent: 'space-between',
            marginBottom: getSize(6, 7, 8, 10, 12),
        },
        summaryLabel: {
            fontFamily: 'Cairo_600SemiBold',
            fontSize: fontSize.sm,
            color: '#64748b',
        },
        summaryValue: {
            fontFamily: 'Cairo_700Bold',
            fontSize: fontSize.base,
            color: COLORS.primary,
        },
        summaryNote: {
            fontFamily: 'Cairo_500Medium',
            fontSize: fontSize.xs,
            color: '#94a3b8',
            textAlign: (isRTL ? 'right' : 'left') as const,
            lineHeight: getSize(14, 15, 16, 18, 20),
        },
        bottomContainer: {
            backgroundColor: 'white',
            borderTopWidth: 1,
            borderTopColor: '#f1f5f9',
        },
        bottomContent: {
            paddingHorizontal: getSize(18, 19, 20, 24, 28),
            paddingVertical: getSize(14, 15, 16, 20, 24),
        },
    });
};
